version: '2'
services:
  app:
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DIRECTORY=app
  database:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d